### ISSUE TITLE
filtering should always be upon ALL-DATA, not paged data

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#111]
Paging should happen AFTER filtering, so you don't, eg, have a page with 2 results and then one with 5 results, etc.

**Comment by dalpal07** [comment]
@WorldsEndless I think that we may need two different options that table users can choose from. In my mind, there is an instantaneous filter option (what we have now) where you can type in the search bar and filters are applied instantly to the current data set. This would probably be most desirable for data sets that are not paged because of the issue you mentioned. The next option would address the problem you just mentioned: a user could type in and set whatever filters they wanted on the data set and then they might click a button that applies those filters. Upon loading, a finely paged data set then displays the results of the filter. This would make more sense for paged data sets because it would be nice for the table to be re-paged, but there would have to be some sort of reset each time the table is re-paged (e.g., the table should jump back at page 1).

**Comment by WorldsEndless** [comment]
What if we just rearrange -- paging ALWAYS occurs after the filtering, so as you filter, you will see the number of pages decrease? 

Then we just have to keep the result submission similar -- eg, the first thing in the current view AFTER it's been reduced by filters remains the first thing on your after-filter view (supposing you've started filtering while on a page viewing, eg, the 75th of your items)

**Comment by dalpal07** [comment]
I think that's a good idea. I'll look into implementing this.
