### ISSUE TITLE
Support full data downloads

### ISSUE THREAD

**Issue by bjamin5** [BYU-ODH/retabled#12]
Needs to support full data downloads.

**EDIT:** ignore the following
~~Note that we have code written that does it the ajax way that should be an option for a user.~~

**Comment by WorldsEndless** [comment]
Needs to expose the data present on a particular view

**Comment by WorldsEndless** [comment]
This should be developer-facing, not user-facing. It should not be explicitly CSV, though perhaps it can provide defaults that are. In other words, everything cd #53 may be okay as a special option that users might utilize as a default, but this issue is primarily about just allowing developers access to the current data view data somehow, which they could use to make in to a CSV if they want to, or could feed it into other things (such as d3js for data viewing, places for further formatting, etc). In short, it just needs to expose the data to the developer so they can do what they want with it. The CSV button is icing on the cake, but not the central idea here.

**Comment by WorldsEndless** [comment]
Make available an atom containing the following https://github.com/BYU-ODH/retabled/blob/3deaaaaa9f98864bcc2501045a94cd4e4afc2ba3/src/retabled/filter.cljc#L60

**Comment by WorldsEndless** [comment]
The result should be an public atom that a dev can download of shape,
```
{:table1 data1 :table2 data2}
```

**Comment by WorldsEndless** [comment]
No -- this library needs do no IO. That is up to whoever is using it.
