### ISSUE TITLE
Add tests for retabled

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#67]
Especially for verifying browser security

**Comment by WorldsEndless** [comment]
for some ideas:

How to run tests in clojurescript | Abhinav Omprakash
https://www.abhinavomprakash.com/posts/running-cljs-tests/

**Comment by WorldsEndless** [comment]
doo runner:
https://github.com/bensu/doo
https://www.agynamix.de/blog/2015-09-22-doo-and-figwheel/

**Comment by WorldsEndless** [comment]
Example of leininger setup that should not require our current /tests directory setup (for the browser startup during dev) to go away: https://github.com/BYU-ODH/flats/blob/dev/project.clj#L67

**Comment by dalpal07** [comment]
As I've been writing tests for retabled, I've realized just how many assumptions we make in the code about getting non-nil values. For example, we receive `col-map` as an argument in the `on-click-filter` function and immediately call `(:valfn col-map)`. If `col-map` is nil, then the website will crash. In order to add safeguards to these functions instead of making assumptions, should we just return from the function and return nil, should we at least print out a statement saying that something was nil that shouldn't have been, or should we throw a specific error?

**Comment by dalpal07** [comment]
@WorldsEndless how in depth do we want these tests for this issue? Do we just want to get some tests out there or do we want to test every function (that makes sense of course) with all possible edge cases? Also, should I change any of our code for this issue or should I just make notes in the test cases about functions we may need to adjust?

**Comment by WorldsEndless** [comment]
The tests should look at the most common error-cases, at least: every test should deal with nil input, and then the obvious cases, as applicable: what if the input is a string? What if it's not? What if there is a very large amount of input? 

Test whatever things occur to you that could make it break
